baseURL = 'https://nicolasfurno.fr'
languageCode = 'fr'
defaultContentLanguage = "fr"
title = 'Le blog de Nicolas Furno'
theme = 'nicolasfurno'
paginate = 12
copyright = "© Nicolas Furno"
timeZone = "Europe/Paris"
enableGitInfo = true


[author]
  name = "Nicolas Furno"
  email = "nicolasfurno@gmail.com"

[menu]
[[menu.main]]
  identifier = 'archives'
  name = 'Archives'
  url = '/archives/'
[[menu.main]]
  identifier = 'recherche'
  name = 'Recherche'
  url = '/recherche/'
[[menu.main]]
  identifier = 'mentions'
  name = 'Mentions légales'
  url = '/mentions-legales/'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]

[permalinks]
  pages = '/:filename/'

[params]
  description = 'Critiques de films, de séries, d’albums, de livres… et tout ce que je veux écrire.'
  title = 'Le blog de Nicolas Furno'


[social]
  twitter = 'nicolasfurno'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true