baseURL = 'https://nicolasfurno.fr'
languageCode = 'fr'
defaultContentLanguage = "fr"
title = 'Le blog de Nicolas Furno'
theme = 'nicolasfurno'
[pagination]
  pagerSize = 12
copyright = "© Nicolas Furno"
timeZone = "Europe/Paris"
enableGitInfo = true

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'À propos'
  url = '/a-propos/'
  weight = 10
[[menu.main]]
  identifier = 'archives'
  name = 'Archives'
  url = '/archives/'
  weight = 20
[[menu.main]]
  identifier = 'mentions'
  name = 'Mentions légales'
  url = '/mentions-legales/'
  weight = 100

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  saga = 'sagas'

[permalinks]
  pages = '/:filename/'

[params]
  description = 'Critiques de films, de séries, d’albums, de livres… et tout ce que je veux écrire.'
  title = 'Le blog de Nicolas Furno'

  [params.author]
    name = "Nicolas Furno"
    email = "nicolasfurno@gmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.getjson]
    dir = ':resourceDir/_gen/'
    maxAge = "536h"