baseURL = 'https://nicolasfurno.fr'
languageCode = 'fr'
defaultContentLanguage = "fr"
title = 'Le blog de Nicolas Furno'
theme = 'nicolasfurno'
paginate = 12
copyright = "© Nicolas Furno"
timeZone = "Europe/Paris"
enableGitInfo = true

[author]
  name = "Nicolas Furno"
  email = "nicolasfurno@gmail.com"