baseURL = 'https://nicolasfurno.fr'
languageCode = 'fr'
title = 'Le blog de Nicolas Furno'
theme = 'nicolasfurno'
paginate = 12
copyright = "© Nicolas Furno"

[author]
  name = "Nicolas Furno"
  email = "nicolasfurno@gmail.com"
